/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univates.projeto_cafeteira_poe;

import javax.swing.JOptionPane;

/**
 *
 * @author juliano.hammes1
 */
public class menu_dono extends javax.swing.JFrame {

    private CafeteiraMachine cafeteira;
    /**
     * Creates new form menu_dono
     */
    public menu_dono(CafeteiraMachine cafeteira) {
    initComponents();
    this.cafeteira = cafeteira;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 28, 28));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("MENU DO DONO");

        jButton1.setBackground(new java.awt.Color(29, 29, 29));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Verificar Saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(29, 29, 29));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Abastecer café");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(29, 29, 29));
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Abastecer água");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(29, 29, 29));
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Abastecer chocolate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(29, 29, 29));
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String mensagem = String.format(
        "Status da Cafeteira:\n\n" +
        "Saldo: R$%.2f\n" +
        "Grãos de Café: %dg\n" +
        "Água: %dml\n" +
        "Chocolate: %dg",
        this.cafeteira.getBalance(),
        this.cafeteira.getCoffeeBean(),
        this.cafeteira.getWater(),
        this.cafeteira.getChocolate()
    );

    JOptionPane.showMessageDialog(this, mensagem, "Status da Máquina", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String amountInput = JOptionPane.showInputDialog(this, "Digite a quantidade de grãos de café para reabastecer:");
        if (amountInput != null && !amountInput.isEmpty()) {
            try {
                int amount = Integer.parseInt(amountInput);
                this.cafeteira.refillCoffeeBean(amount); // Chama o método da instância
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, digite apenas números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String amountInput = JOptionPane.showInputDialog(this, "Digite a quantidade de água para reabastecer:");
        if (amountInput != null && !amountInput.isEmpty()) {
            try {
                int amount = Integer.parseInt(amountInput);
                this.cafeteira.refillWater(amount); // Chama o método da instância
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, digite apenas números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String amountInput = JOptionPane.showInputDialog(this, "Digite a quantidade de chocolate para reabastecer:");
        if (amountInput != null && !amountInput.isEmpty()) {
            try {
                int amount = Integer.parseInt(amountInput);
                this.cafeteira.refillChocolate(amount); // Chama o método da instância
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, digite apenas números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        interface_cafeteira telaPrincipal = new interface_cafeteira(this.cafeteira); // Volta para a tela principal
        telaPrincipal.setVisible(true);
        telaPrincipal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
